spring:
  redis:
    # redis服务器IP地址
    host: 127.0.0.1
    # redis服务器端口号
    port: 6379
    # redis服务器连接密码（默认为空）
    password:
    # redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        # lettuce连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # lettuce连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        # lettuce连接池中的最大空闲连接数
        max-idle: 20
        # lettuce连接池中的最小空闲连接数
        min-idle: 2